#!/usr/bin/env python

# Copyright 2019 John-Robert Scholz
#
# This file is part of Seisglitch.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# -*- coding: utf-8 -*-


"""
..
"""


#####  python modules import  #####
import os
import sys
import argparse
import matplotlib.pyplot as plt

#####  obspy modules import  #####
from obspy import read

#####  seisglitch modules import  #####
from seisglitch import detect, plot, remove, util



### PARSING ARGUEMENTS
parser = argparse.ArgumentParser(
    description = """
                  SEISGLITCH PROGRAM
                  """)

parser.add_argument('mode', 
        metavar = 'MODE',
        type    = str,
        help    = """
                  Choose which Seisglitch mode to run. 
                  Choices: 'detect', 'plot', 'remove', 'download', 'decimate', or 'merge'.
                  """,
        choices = ['detect', 'plot', 'remove', 'download', 'decimate', 'merge'])

parser.add_argument('config_file', 
        metavar = 'CONFIG_FILE',
        type    = str,
        help    = """
                  Choose config file for specific parameters.
                  """)

args   = vars( parser.parse_args() )
mode   = args['mode'].lower()
config = args['config_file']



### EXECUTE ACCORDING TO SPECIFIED PARAMETERS
params = util.read_config(config)


if mode=='detect':

    waveform_files        = params['detect']['waveform_files']
    detect_params         = params['detect']['detector']

    detect.detect( *waveform_files, **detect_params )


elif mode=='plot':
    
    waveform_files        = params['detect']['waveform_files']
    inventory_file        = params['detect']['detector']['inventory_file']
    glitch_length         = params['detect']['detector']['glitch_length']

    glitch_detector_files = params['plot']['glitch_detector_files']
    plot_params           = params['plot']['plotter']


    plot.plot_glitch_detector(  *glitch_detector_files, **plot_params, **params['plot']['glitch_detector_plot'], waveform_files=waveform_files)
    plot.plot_glitch_overview(  *glitch_detector_files, **plot_params, **params['plot']['glitch_overview_plot'], waveform_files=waveform_files, glitch_length=glitch_length )
    plot.plot_glitch_LMST_sol(  *glitch_detector_files, **plot_params, **params['plot']['glitch_LMST_sol_plot'])
    plot.plot_glitch_gutenberg( *glitch_detector_files, **plot_params, **params['plot']['glitch_gutenberg_plot'] )
    plot.plot_glitch_waveform(  *glitch_detector_files, **plot_params, **params['plot']['glitch_waveform_plot'], waveform_files=waveform_files)
    plot.plot_glitch_align(     *glitch_detector_files, **plot_params, **params['plot']['glitch_align_plot'],    waveform_files=waveform_files)
    plot.plot_glitch_ppol(                              **plot_params, **params['plot']['glitch_ppol_plot'],     waveform_files=waveform_files, inventory_file=inventory_file, glitch_length=glitch_length)

    if plot_params['show']:
      plt.show()
    plt.close()


elif mode=='remove':

    inventory_file        = params['detect']['detector']['inventory_file']
    glitch_length         = params['detect']['detector']['glitch_length']

    glitch_detector_files = params['remove']['glitch_detector_files']
    waveform_files        = params['remove']['waveform_files']
    remove_params         = params['remove']['remover']

    remove.remove( *glitch_detector_files, waveform_files=waveform_files, inventory_file=inventory_file, glitch_length=glitch_length, **remove_params )


elif mode=='download':

    kwargs = params['download']
    util.download_data(**kwargs)


elif mode=='decimate':

    waveform_files        = params['decimate']['waveform_files']
    
    decimation_factors    = params['decimate']['decimation_factors']
    final_network         = params['decimate']['final_network']
    final_station         = params['decimate']['final_station']
    final_location        = params['decimate']['final_location']
    final_bandcode        = params['decimate']['final_bandcode']

    for file in waveform_files:

        stream = read(file)
        print()
        print(u'File: %s' % file)
        print(u'Found %s trace. Handling ..' % len(stream))

        for trace in stream.select(channel='?[LMH]?'):
            for decimation_factor in decimation_factors:
                util.decimate_SEIS(trace, decimation_factor, verbose=False)

            if final_network:
                trace.stats.network = final_network

            if final_station:
                trace.stats.station = final_station

            if final_location:
                trace.stats.location = final_location

            if final_bandcode:
                trace.stats.channel = final_bandcode + trace.stats.channel[1:]

        file_path  = os.path.dirname(file)
        file_name  = os.path.basename(file)
        outfile    = os.path.join( file_path, 'decimated_' + file_name)
        stream.write(outfile)

        print(u'File out: %s' % outfile)
        print()

    print(u'Finished.')


elif mode=='merge':

    glitch_detector_files = params['merge']['glitch_detector_files']
    if not glitch_detector_files:
        waveform_files        = params['detect']['waveform_files']        
        glitch_detector_files = [os.path.join( os.path.dirname(file), 'glitches_' + '.'.join(os.path.basename(file).split('.')[:-1]) + '.txt' ) for file in waveform_files]

    outfile               = params['merge']['outfile']
    starttime_sort        = params['merge']['starttime_sort']
    multiples_out         = params['merge']['multiples_out']

    util.merge_glitch_detector_files(glitch_detector_files, outfile, starttime_sort=starttime_sort, multiples_out=multiples_out)