#!/usr/bin/env python

# Copyright 2019 John-Robert Scholz
#
# This file is part of Seisglitch.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# -*- coding: utf-8 -*-


"""
..
"""


#####  python modules import  #####
import sys
import argparse


#####  seisglitch modules import  #####
from seisglitch import detect, plot
from ppol.util import read_config



### PARSING ARGUEMENTS
parser = argparse.ArgumentParser(
    description = """
                  SEISGLITCH PROGRAM
                  """)

parser.add_argument('mode', 
        metavar = 'MODE',
        type    = str,
        help    = """
                  Choose which Seisglitch mode to run. 
                  Choices: 'detect', 'plot', 'remove', or 'evaluate'.
                  """,
        choices = ['detect', 'plot', 'remove', 'evaluate'])

parser.add_argument('config_file', 
        metavar = 'CONFIG_FILE',
        type    = str,
        help    = """
                  Choose config file for specific parameters.
                  """)

parser.add_argument('-f','--files', 
           type = str,
           help = """
                  Specify one or more files (either data or
                  results file) to run specified `MODE` on.
                  """,
          nargs ='+',
        default = None,
       required = True)


args        = vars( parser.parse_args() )

mode        = args['mode'].lower()
params      = read_config( args['config_file'] )
files       = args['files']




### EXECUTE ACCORDING TO SPECIFIED PARAMETERS
if mode=='detect':

    detect_params = params['detect']
    detect.glitch_detector( *files, **detect_params )


elif mode=='plot':

    plott_params = params['plot']
    plot.glitch_overview_plot(  *files, **plot_params['glitch_overview_plot']  )
    plot.glitch_gutenberg_plot( *files, **plot_params['glitch_gutenberg_plot'] )
    plot.glitch_envelope_plot(  *files, **plot_params['glitch_envelope_plot']  )
    plot.glitch_XoverBAZ_plot(  *files, **plot_params['glitch_XoverBAZ_plot']  )


elif mode=='remove':
  pass


elif mode=='evaluate':
  pass